# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file Project/pom.xml
      
    - name: 'Utils jar'
      uses: actions/upload-artifact@v2
      with:
        name: "Utils.jar"
        path: Project/Utils/target/Utils-1.0-SNAPSHOT.jar
        
    - name: 'Nameserver jar'
      uses: actions/upload-artifact@v2
      with:
        name: "Nameserver.jar"
        path: Project/Nameserver/target/Nameserver-0.0.1-SNAPSHOT.jar
        
    - name: 'Client jar'
      uses: actions/upload-artifact@v2
      with:
        name: "Client.jar"
        path: Project/Client/target/Client-1.0-SNAPSHOT.jar
